version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8002:8001'

  dynamodb:
    image: ryanratcliff/dynamodb
    ports:
      - "8000:8000"