# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install yarn -g 
    - run: yarn && yarn test && yarn test:e2e
    - run: yarn build
    - run: sudo apt update
    - run: sudo apt install aws-shell
    - run: printf "${{secrets.AWS_API_KEY}}\n${{secrets.AWS_API_SECRET}}\nus-east-1\njson\n" | aws configure
    - run: ls ~/.aws && GITHUB_TOKEN="${{secrets.GITHUB_TOKEN}}" CACHE_URL="${{secrets.CACHE_URL}}" YUQUE_TOKEN="${{secrets.YUQUE_TOKEN}}" yarn deploy
